function make_dsc_rois_subject(type, dscfile, mniregionsfile, mnitumorregionsfile)
    
    % For uncorrected and corrected DSC
    %make_dsc_rois_subject('e1', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/dsc.nii', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/mniroisd/mnirois.nii', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/mniroisd/tumor.nii')

    [dscpath, dscfilename, dscfileext] = fileparts(dscfile);
    [~, mniregionsfilename, mniregionsfileext] = fileparts(mniregionsfile);
    [~, mnitumorregionsfilename, mnitumorregionsfileext] = ...
        fileparts(mnitumorregionsfile);
    
    wd = dscpath;

    % Not GT ROIs
    
    % 1.

    estimate_deformation_to_mni(dscfile);
    
    dsc_deformationfile = ...
        strcat(wd, '/y_', dscfilename, dscfileext);
    
    % 2.

    compute_inverse(dsc_deformationfile, ...
                    dscfile, ...
                    strcat('inv_y_', dscfilename), ...
                    wd);
	
    inverted_dsc_deformationfile = ...
        strcat(wd, '/y_inv_y_', dscfilename, dscfileext);
	
	% 3.
	
    apply_deformation(inverted_dsc_deformationfile, ...
                      mniregionsfile, ...
                      wd, ...
                      strcat('dsc_deformed_', type, '_'));
    
    apply_deformation(inverted_dsc_deformationfile, ...
                      mnitumorregionsfile, ...
                      wd, ...
                      strcat('dsc_deformed_', type, '_'));
                  
    dsc_deformed_mniroisfile = strcat(wd, ...
                                      '/dsc_deformed_', ...
                                      type, ...
                                      '_', ...
                                      mniregionsfilename, ...
                                      mniregionsfileext);
                                  
    dsc_deformed_mnitumorroisfile = strcat(wd, ...
                                      '/dsc_deformed_', ...
                                      type, ...
                                      '_', ...
                                      mnitumorregionsfilename, ...
                                      mnitumorregionsfileext);
	roisfile = strcat(wd, '/rois_', type, mniregionsfileext);
    tumorroisfile = strcat(wd, '/tumorrois_', type, mnitumorregionsfileext);
    movefile(dsc_deformed_mniroisfile, roisfile);
    movefile(dsc_deformed_mnitumorroisfile, tumorroisfile);
    
    % Clean up
    delete(inverted_dsc_deformationfile);
    delete(dsc_deformationfile);
    
end