function make_gt_dsc_rois_subject(type, dscfile, flairfile, mniregionsfile, flairtumorregionsfile)
    
    % For uncorrected DSC
    %make_gt_dsc_rois_subject('e1', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/dsc.nii', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/flaird/flair.nii', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/mniroisd/mnirois.nii', '/media/loek/HDD3TB1/data/roi-example-topup-372114315/flaird/tumor.nii')

    [dscpath, ~, ~] = fileparts(dscfile);
    [~, flairfilename, flairfileext] = fileparts(flairfile);
    [~, mniregionsfilename, mniregionsfileext] = fileparts(mniregionsfile);
    [~, flairtumorregionsfilename, flairtumorregionsfileext] = ...
        fileparts(flairtumorregionsfile);
    
    wd = dscpath;
    
    % GT ROIs
    
    flairfile_copied = ...
        strcat(wd, '/', type, '_', flairfilename, flairfileext);
    copyfile(flairfile, flairfile_copied);
    
    % 1.
    
    estimate_deformation_to_mni(flairfile_copied);
    
    flair_deformationfile = ...
        strcat(wd, '/y_', type, '_', flairfilename, flairfileext);
    
    % 2.
    
    compute_inverse(flair_deformationfile, ...
                    flairfile_copied, ...
                    strcat('inv_y_', type, '_', flairfilename), ...
                    wd);
    
    inverted_flair_deformationfile = ...
        strcat(wd, '/y_inv_y_', type, '_', flairfilename, flairfileext);
    
    % 3.
    
    apply_deformation(inverted_flair_deformationfile, ...
                      mniregionsfile, ...
                      wd, ...
                      strcat('flair_deformed_', type, '_'));

    % Estimate step in rigid registration
    % will modify "src" and "other_files"
    flairfile_copied_copied = ...
        strcat(wd, '/_', type, '_', flairfilename, flairfileext);
    flair_deformed_mniroisfile = strcat(wd, ...
                                        '/flair_deformed_', ...
                                        type, ...
                                        '_', ...
                                        mniregionsfilename, ...
                                        mniregionsfileext);
    flair_deformed_mniroisfile_copied = strcat(wd, ...
                                               '/_flair_deformed_', ...
                                               type, ...
                                               '_', ...
                                               mniregionsfilename, ...
                                               mniregionsfileext);
    flairtumorregionsfile_copied = strcat(wd, ...
                                          '/_', ...
                                          type, ...
                                          '_', ...
                                          flairtumorregionsfilename, ...
                                          flairtumorregionsfileext);
    copyfile(flairfile_copied, flairfile_copied_copied);
    copyfile(flair_deformed_mniroisfile, flair_deformed_mniroisfile_copied);
    copyfile(flairtumorregionsfile, flairtumorregionsfile_copied);

    % 4.
    
    other_files = {
        flair_deformed_mniroisfile_copied
        flairtumorregionsfile_copied};
    
    coreg_est_reslice(dscfile, ...
                      flairfile_copied_copied, ...
                      other_files, ...
                      0); % knn

    resliced_flairfile = ...
        strcat(wd, '/r_', type, '_', flairfilename, flairfileext);
                  
    resliced_flair_deformed_mniroisfile_copied = ...
                                    strcat(wd, ...
                                           '/r_flair_deformed_', ...
                                           type, ...
                                           '_', ...
                                           mniregionsfilename, ...
                                           mniregionsfileext);
    resliced_flairtumorregionsfile_copied = ...
                                    strcat(wd, ...
                                           '/r_', ...
                                           type, ...
                                           '_', ...
                                           flairtumorregionsfilename, ...
                                           flairtumorregionsfileext);
    gtroisfile = strcat(wd, '/gtrois_', type, mniregionsfileext);
    gttumorroisfile = strcat(wd, '/gttumorrois_', type, flairtumorregionsfileext);
    movefile(resliced_flair_deformed_mniroisfile_copied, gtroisfile);
    movefile(resliced_flairtumorregionsfile_copied, gttumorroisfile);
    
    % Clean up    
    delete(resliced_flairfile);
    delete(flairtumorregionsfile_copied);
    delete(inverted_flair_deformationfile);
    delete(flair_deformationfile);
    delete(flair_deformed_mniroisfile_copied);
    delete(flairfile_copied_copied);
    delete(flairfile_copied);
    
end